apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on:
  workflow_call:
    inputs:
      artifact-id: 
        type: string
      environment: 
        type: string

jobs:
  register_artifact_version_to_env:
    steps:
      - name: Register_deployed_artifact
        with:
          artifact-id: ${{ inputs.artifact-id }}
          target-environment: $ {{ inputs.environment }}
        uses: cloudbees-io/register-deployed-artifact@v2